In [1]:
import pandas as pd
import numpy as np

In [2]:
ls=pd.read_csv('../inside_airbnb_data/listings.csv')

## Listings Clean

In [3]:
import re

ls.drop(columns= ['id', 'host_id','host_name', 'neighbourhood_group', 'last_review','license','reviews_per_month'], inplace=True)

def extract_info(text):
    # Extract rating
    rating_match = re.search(r'★(\d+\.\d+)', text)
    rating = float(rating_match.group(1)) if rating_match else 'unknown'
    
    # Extract number of bedrooms
    bedroom_match = re.search(r'(\d+)\sbedrooms?', text)
    bedrooms = int(bedroom_match.group(1)) if bedroom_match else 'unknown'
    
    # Extract number of baths
    bath_match = re.search(r'(\d+)\s(private\s)?baths?', text)
    baths = int(bath_match.group(1)) if bath_match else 'unknown'
    
    return rating, bedrooms, baths

In [4]:
ls[['rating', 'bedrooms', 'baths']] = ls['name'].apply(lambda x: pd.Series(extract_info(x)))
ls.drop(columns='name', inplace=True)
ls

,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,calculated_host_listings_count,availability_365,number_of_reviews_ltm,rating,bedrooms,baths
0,Historic Anacostia,38.863390,-76.988890,Private room,67.0,31,84,1,365,3,4.64,1.0,1.0
1,"Edgewood, Bloomingdale, Truxton Circle, Eckington",38.911950,-77.004560,Private room,66.0,1,495,5,252,46,4.83,1.0,1.0
2,"Capitol Hill, Lincoln Park",38.887190,-76.994720,Private room,135.0,7,58,2,321,6,4.85,1,unknown
3,"Eastland Gardens, Kenilworth",38.905850,-76.944690,Private room,56.0,30,102,2,179,0,4.66,1,unknown
4,"Ivy City, Arboretum, Trinidad, Carver Langston",38.912170,-76.992490,Private room,2500.0,1125,30,3,365,0,4.74,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6848,"Shaw, Logan Circle",38.906922,-77.024228,Entire home/apt,173.0,32,0,234,105,0,unknown,1,1
6849,"Brightwood Park, Crestwood, Petworth",38.949640,-77.016980,Private room,79.0,1,0,28,267,0,unknown,1,1
6850,"Brightwood Park, Crestwood, Petworth",38.951456,-77.016104,Entire home/apt,87.0,1,0,28,270,0,unknown,1,1
6851,"Brightwood Park, Crestwood, Petworth",38.951410,-77.016220,Entire home/apt,79.0,1,0,28,270,0,unknown,1,1
6852,"Ivy City, Arboretum, Trinidad, Carver Langston",38.909047,-76.984541,Private room,143.0,1,0,3,270,0,unknown,2,1

In [5]:
ls.to_csv('listings_cleaned.csv', index=False)